/**
 * Desktop-only UI strings for the seven shipped languages, English canonical.
 * Upstream strings stay inside the upstream locale mechanism; this table
 * covers only the surfaces the desktop owns (onboarding, runtime status,
 * settings seats, failure and diagnostics copy).
 *
 * @module @deepseek-ai/dsh-desktop-client/ui/strings
 */

import { useSyncExternalStore } from 'react'
import { desktopLocale, type DesktopLanguage } from '../locale.ts'

/** Every desktop-owned UI string key, English canonical and seven locales. */
export type DesktopStringKey =
  | 'onboarding.welcome.title'
  | 'onboarding.welcome.body'
  | 'onboarding.welcome.continue'
  | 'onboarding.provider.title'
  | 'onboarding.provider.apiKey'
  | 'onboarding.provider.baseUrl'
  | 'onboarding.provider.save'
  | 'onboarding.back'
  | 'onboarding.workspace.title'
  | 'onboarding.workspace.body'
  | 'onboarding.workspace.pick'
  | 'status.starting'
  | 'status.running'
  | 'status.restarting'
  | 'status.stopped'
  | 'status.failed'
  | 'status.stopping'
  | 'failure.title'
  | 'failure.restart'
  | 'failure.logs'
  | 'settings.language'
  | 'settings.language.system'
  | 'settings.language.english'
  | 'settings.language.italian'
  | 'settings.language.chinese'
  | 'settings.language.spanish'
  | 'settings.language.french'
  | 'settings.language.german'
  | 'settings.language.portuguese'
  | 'settings.advanced'
  | 'settings.desktopVersion'
  | 'settings.harnessVersion'
  | 'settings.protocol'
  | 'settings.runtimeState'
  | 'settings.restart'
  | 'settings.logs'
  | 'settings.diagnostics'
  | 'settings.title'
  | 'settings.close'
  | 'credentials.title'
  | 'credentials.configured'
  | 'credentials.notConfigured'
  | 'credentials.replace'
  | 'credentials.replacePlaceholder'
  | 'credentials.replaceSave'
  | 'credentials.remove'
  | 'credentials.removeConfirm'
  | 'credentials.removeConfirmYes'
  | 'credentials.removeConfirmNo'
  | 'settings.baseUrl'
  | 'settings.baseUrlPlaceholder'
  | 'settings.baseUrlSave'
  | 'settings.baseUrlInvalid'
  | 'settings.copy'
  | 'notification.approval'
  | 'notification.approvalBody'
  | 'notification.question'
  | 'notification.questionBody'
  | 'notification.taskCompleted'
  | 'notification.taskCompletedBody'
  | 'notification.runtimeFailed'
  | 'notification.runtimeFailedBody'
  | 'error.credentialEmpty'
  | 'error.unknown'
  | 'inspector.toggle'
  | 'inspector.files'
  | 'inspector.changes'
  | 'inspector.terminal'
  | 'inspector.plan'
  | 'inspector.jobs'
  | 'inspector.subagents'
  | 'files.refresh'
  | 'files.reveal'
  | 'files.empty'
  | 'files.searchPlaceholder'
  | 'files.binary'
  | 'files.back'
  | 'files.loadError'
  | 'files.previewEmpty'
  | 'changes.noRepo'
  | 'changes.gitMissing'
  | 'changes.branch'
  | 'changes.clean'
  | 'changes.filesCount'
  | 'changes.added'
  | 'changes.removed'
  | 'changes.untracked'
  | 'changes.empty'
  | 'changes.staged'
  | 'changes.stagedEmpty'
  | 'changes.changes'
  | 'changes.conflicted'
  | 'changes.stage'
  | 'changes.unstage'
  | 'changes.staging'
  | 'changes.unstaging'
  | 'changes.dirtyStageWarning'
  | 'changes.opFailed'
  | 'changes.outsideWorkspace'
  | 'changes.discard'
  | 'changes.discardTitle'
  | 'changes.discardConsequence'
  | 'changes.discardConsequenceStaged'
  | 'changes.discardBlockedDirty'
  | 'changes.discarding'
  | 'changes.stateChanged'
  | 'changes.cannotDiscard'
  | 'changes.cancel'
  | 'changes.unstaged'
  | 'changes.diffMode'
  | 'changes.noStagedChanges'
  | 'changes.noUnstagedChanges'
  | 'changes.binaryChanged'
  | 'changes.diffTooLarge'
  | 'changes.prevFile'
  | 'changes.nextFile'
  | 'changes.openFile'
  | 'changes.renameOnly'
  | 'changes.diffSelectFile'
  | 'changes.diffLoading'
  | 'changes.untrackedNoDiff'
  | 'changes.diffConflictReadOnly'
  | 'terminal.noSession'
  | 'terminal.new'
  | 'terminal.close'
  | 'terminal.inputHint'
  | 'terminal.exited'
  | 'terminal.spawnError'
  | 'plan.empty'
  | 'plan.pending'
  | 'plan.active'
  | 'plan.completed'
  | 'jobs.empty'
  | 'jobs.killed'
  | 'jobs.failed'
  | 'jobs.stopped'
  | 'subagents.empty'
  | 'subagents.main'
  | 'subagents.running'
  | 'subagents.completed'
  | 'editor.backToConversation'
  | 'editor.empty'
  | 'editor.save'
  | 'editor.saving'
  | 'editor.saved'
  | 'editor.dirty'
  | 'editor.saveError'
  | 'editor.conflictState'
  | 'editor.conflictBody'
  | 'editor.conflictReload'
  | 'editor.conflictKeep'
  | 'editor.closeTab'
  | 'editor.unsavedBody'
  | 'editor.unsavedCancel'
  | 'editor.unsavedDiscard'
  | 'editor.unsavedSave'
  | 'editor.readOnly'
  | 'editor.externalState'
  | 'editor.externalBody'
  | 'editor.externalReload'
  | 'editor.externalKeep'
  | 'editor.deletedState'
  | 'editor.deletedBody'
  | 'editor.deletedClose'
  | 'editor.saveAll'
  | 'quickOpen.placeholder'
  | 'quickOpen.indexing'
  | 'quickOpen.empty'
  | 'quickOpen.noMatch'
  | 'quickOpen.hint'
  | 'quitGuard.title'
  | 'quitGuard.body'
  | 'quitGuard.cancel'
  | 'quitGuard.discard'
  | 'quitGuard.saveAll'
  | 'quitGuard.saveFailed'
  | 'editor.large'

/** English canonical desktop dictionary. */
export const en: Record<DesktopStringKey, string> = {
  'onboarding.welcome.title': 'Welcome to Harness Desktop',
  'onboarding.welcome.body': 'AI coding powered by DeepSeek Harness. Unofficial desktop client.',
  'onboarding.welcome.continue': 'Continue',
  'onboarding.provider.title': 'Connect DeepSeek',
  'onboarding.provider.apiKey': 'API Key',
  'onboarding.provider.baseUrl': 'Base URL (optional)',
  'onboarding.provider.save': 'Save to Keychain',
  'onboarding.back': 'Back',
  'onboarding.workspace.title': 'Choose a project',
  'onboarding.workspace.body': 'Select the folder Harness will work in. The native macOS picker opens next.',
  'onboarding.workspace.pick': 'Open Folder Picker',
  'status.starting': 'Starting Harness…',
  'status.running': 'Connected',
  'status.restarting': 'Restarting Harness…',
  'status.stopped': 'Harness stopped',
  'status.failed': 'Harness unavailable',
  'status.stopping': 'Stopping Harness…',
  'failure.title': 'Harness stopped unexpectedly.',
  'failure.restart': 'Restart Harness',
  'failure.logs': 'Open Logs',
  'settings.language': 'Language',
  'settings.language.system': 'System',
  'settings.language.english': 'English',
  'settings.language.italian': 'Italiano',
  'settings.language.chinese': '中文',
  'settings.language.spanish': 'Español',
  'settings.language.french': 'Français',
  'settings.language.german': 'Deutsch',
  'settings.language.portuguese': 'Português (Brasil)',
  'settings.advanced': 'Advanced',
  'settings.desktopVersion': 'Desktop version',
  'settings.harnessVersion': 'Harness version',
  'settings.protocol': 'Desktop protocol',
  'settings.runtimeState': 'Runtime state',
  'settings.restart': 'Restart Harness',
  'settings.logs': 'Open Logs',
  'settings.diagnostics': 'Copy Diagnostics',
  'settings.title': 'Settings',
  'settings.close': 'Close',
  'credentials.title': 'DeepSeek Credentials',
  'credentials.configured': 'API key configured in the macOS Keychain.',
  'credentials.notConfigured': 'No API key configured.',
  'credentials.replace': 'Replace API Key',
  'credentials.replacePlaceholder': 'New API key',
  'credentials.replaceSave': 'Save',
  'credentials.remove': 'Remove API Key',
  'credentials.removeConfirm': 'Remove the stored API key? The assistant will stop authenticating until a new key is saved.',
  'credentials.removeConfirmYes': 'Remove',
  'credentials.removeConfirmNo': 'Cancel',
  'settings.baseUrl': 'Base URL',
  'settings.baseUrlPlaceholder': 'https://api.deepseek.com',
  'settings.baseUrlSave': 'Save',
  'settings.baseUrlInvalid': 'The Base URL must use https://',
  'settings.copy': 'Copy',
  'notification.approval': 'Approval required',
  'notification.approvalBody': 'Harness is waiting for a permission decision.',
  'notification.question': 'Input required',
  'notification.questionBody': 'Harness asked a question and is waiting for an answer.',
  'notification.taskCompleted': 'Task completed',
  'notification.taskCompletedBody': 'The assistant finished the current task.',
  'notification.runtimeFailed': 'Harness stopped unexpectedly',
  'notification.runtimeFailedBody': 'Open Harness Desktop for recovery options.',
  'error.credentialEmpty': 'API key must not be empty',
  'error.unknown': 'Something went wrong',
  'inspector.toggle': 'Inspector',
  'inspector.files': 'Files',
  'inspector.changes': 'Changes',
  'inspector.terminal': 'Terminal',
  'inspector.plan': 'Plan',
  'inspector.jobs': 'Jobs',
  'inspector.subagents': 'Subagents',
  'files.refresh': 'Refresh',
  'files.reveal': 'Reveal in Finder',
  'files.empty': 'No files',
  'files.searchPlaceholder': 'Search in file…',
  'files.binary': 'Binary files cannot be previewed',
  'files.back': 'Back',
  'files.loadError': 'Could not load the file',
  'files.previewEmpty': 'Select a file to preview',
  'changes.noRepo': 'The workspace is not a Git repository',
  'changes.gitMissing': 'git not found',
  'changes.branch': 'Branch',
  'changes.clean': 'Working tree clean',
  'changes.filesCount': '{count} changed files',
  'changes.added': 'Additions',
  'changes.removed': 'Deletions',
  'changes.untracked': 'Untracked files',
  'changes.empty': 'No changes',
  'changes.staged': 'Staged Changes',
  'changes.stagedEmpty': 'Nothing staged',
  'changes.changes': 'Changes',
  'changes.conflicted': 'Conflicts',
  'changes.stage': 'Stage',
  'changes.unstage': 'Unstage',
  'changes.staging': 'Staging…',
  'changes.unstaging': 'Unstaging…',
  'changes.dirtyStageWarning': 'Unsaved editor changes are not included. Stage will use the saved file on disk.',
  'changes.opFailed': 'The Git operation failed',
  'changes.outsideWorkspace': 'Outside workspace',
  'changes.discard': 'Discard Changes',
  'changes.discardTitle': 'Discard changes?',
  'changes.discardConsequence': 'This restores the saved worktree file from Git and cannot be undone by Harness Desktop.',
  'changes.discardConsequenceStaged': 'This restores the worktree file to the staged version. Staged changes remain staged.',
  'changes.discardBlockedDirty': 'This file has unsaved editor changes. Save or discard the editor draft before discarding changes from disk.',
  'changes.discarding': 'Discarding…',
  'changes.stateChanged': 'The Git state changed. The file list was refreshed; try again.',
  'changes.cannotDiscard': 'Discard is not available for this file state.',
  'changes.cancel': 'Cancel',
  'changes.unstaged': 'Unstaged',
  'changes.diffMode': 'Diff mode',
  'changes.noStagedChanges': 'No staged changes',
  'changes.noUnstagedChanges': 'No unstaged changes',
  'changes.binaryChanged': 'Binary file changed',
  'changes.diffTooLarge': 'Diff too large to display',
  'changes.prevFile': 'Previous file',
  'changes.nextFile': 'Next file',
  'changes.openFile': 'Open File',
  'changes.renameOnly': 'Rename only — no content change',
  'changes.diffSelectFile': 'Select a file to view its diff',
  'changes.diffLoading': 'Loading diff…',
  'changes.untrackedNoDiff': 'Untracked file — no Git diff available',
  'changes.diffConflictReadOnly': 'conflict state is read-only',
  'terminal.noSession': 'Open a session to use the terminal',
  'terminal.new': 'New terminal',
  'terminal.close': 'Close terminal',
  'terminal.inputHint': 'Type here and press Enter',
  'terminal.exited': 'Process exited',
  'terminal.spawnError': 'Could not start the terminal',
  'plan.empty': 'No structured plan',
  'plan.pending': 'Pending',
  'plan.active': 'Active',
  'plan.completed': 'Completed',
  'jobs.empty': 'No background jobs',
  'jobs.killed': 'Killed',
  'jobs.failed': 'Failed',
  'jobs.stopped': 'Stopped',
  'subagents.empty': 'No subagents',
  'subagents.main': 'Main agent',
  'subagents.running': 'Running',
  'subagents.completed': 'Completed',
  'editor.backToConversation': 'Back to conversation',
  'editor.empty': 'No open files',
  'editor.save': 'Save',
  'editor.saving': 'Saving…',
  'editor.saved': 'Saved',
  'editor.dirty': 'Unsaved changes',
  'editor.saveError': 'Save failed',
  'editor.conflictState': 'Conflict',
  'editor.conflictBody': 'The file changed on disk since it was opened. Reload to see the newer content, or keep editing.',
  'editor.conflictReload': 'Reload from disk',
  'editor.conflictKeep': 'Keep editing',
  'editor.closeTab': 'Close tab',
  'editor.unsavedBody': 'This file has unsaved changes.',
  'editor.unsavedCancel': 'Cancel',
  'editor.unsavedDiscard': 'Discard changes',
  'editor.unsavedSave': 'Save',
  'editor.readOnly': 'Read only',
  'editor.large': 'File too large to edit',
  'editor.externalState': 'Changed externally',
  'editor.externalBody': 'This file changed on disk. Your edits are kept in memory.',
  'editor.externalReload': 'Review / Reload',
  'editor.externalKeep': 'Keep my changes',
  'editor.deletedState': 'Deleted',
  'editor.deletedBody': 'This file was deleted on disk. The tab keeps its content; nothing is recreated automatically.',
  'editor.deletedClose': 'Close tab',
  'editor.saveAll': 'Save All',
  'quickOpen.placeholder': 'Search files…',
  'quickOpen.indexing': 'Indexing workspace…',
  'quickOpen.empty': 'No files in this workspace',
  'quickOpen.noMatch': 'No matching files',
  'quickOpen.hint': '↑ ↓ navigate · Enter open · Esc close',
  'quitGuard.title': 'Unsaved changes',
  'quitGuard.body': 'Some files have unsaved changes. Quit now?',
  'quitGuard.cancel': 'Cancel',
  'quitGuard.discard': 'Discard and Quit',
  'quitGuard.saveAll': 'Save All and Quit',
  'quitGuard.saveFailed': 'Some files could not be saved (stale version). Nothing was discarded.',
}

/** Italian dictionary, complete against the English key set. */
export const it: Record<DesktopStringKey, string> = {
  'onboarding.welcome.title': 'Benvenuto in Harness Desktop',
  'onboarding.welcome.body': 'Programmazione con AI basata su DeepSeek Harness. Client desktop non ufficiale.',
  'onboarding.welcome.continue': 'Continua',
  'onboarding.provider.title': 'Connetti DeepSeek',
  'onboarding.provider.apiKey': 'Chiave API',
  'onboarding.provider.baseUrl': 'Base URL (facoltativa)',
  'onboarding.provider.save': 'Salva nel Portachiavi',
  'onboarding.back': 'Indietro',
  'onboarding.workspace.title': 'Scegli un progetto',
  'onboarding.workspace.body': 'Seleziona la cartella in cui Harness lavorerà. Si apre il selettore nativo di macOS.',
  'onboarding.workspace.pick': 'Apri selettore cartella',
  'status.starting': 'Avvio di Harness…',
  'status.running': 'Connesso',
  'status.restarting': 'Riavvio di Harness…',
  'status.stopped': 'Harness fermo',
  'status.failed': 'Harness non disponibile',
  'status.stopping': 'Arresto di Harness…',
  'failure.title': 'Harness si è arrestato in modo imprevisto.',
  'failure.restart': 'Riavvia Harness',
  'failure.logs': 'Apri i log',
  'settings.language': 'Lingua',
  'settings.language.system': 'Sistema',
  'settings.language.english': 'English',
  'settings.language.italian': 'Italiano',
  'settings.language.chinese': '中文',
  'settings.language.spanish': 'Español',
  'settings.language.french': 'Français',
  'settings.language.german': 'Deutsch',
  'settings.language.portuguese': 'Português (Brasil)',
  'settings.advanced': 'Avanzate',
  'settings.desktopVersion': 'Versione desktop',
  'settings.harnessVersion': 'Versione Harness',
  'settings.protocol': 'Protocollo desktop',
  'settings.runtimeState': 'Stato runtime',
  'settings.restart': 'Riavvia Harness',
  'settings.logs': 'Apri i log',
  'settings.diagnostics': 'Copia diagnostica',
  'settings.title': 'Impostazioni',
  'settings.close': 'Chiudi',
  'credentials.title': 'Credenziali DeepSeek',
  'credentials.configured': 'Chiave API configurata nel Portachiavi di macOS.',
  'credentials.notConfigured': 'Nessuna chiave API configurata.',
  'credentials.replace': 'Sostituisci chiave API',
  'credentials.replacePlaceholder': 'Nuova chiave API',
  'credentials.replaceSave': 'Salva',
  'credentials.remove': 'Rimuovi chiave API',
  'credentials.removeConfirm': 'Rimuovere la chiave API salvata? L’assistente smetterà di autenticarsi finché non viene salvata una nuova chiave.',
  'credentials.removeConfirmYes': 'Rimuovi',
  'credentials.removeConfirmNo': 'Annulla',
  'settings.baseUrl': 'Base URL',
  'settings.baseUrlPlaceholder': 'https://api.deepseek.com',
  'settings.baseUrlSave': 'Salva',
  'settings.baseUrlInvalid': 'La Base URL deve usare https://',
  'settings.copy': 'Copia',
  'notification.approval': 'Approvazione richiesta',
  'notification.approvalBody': 'Harness attende una decisione sui permessi.',
  'notification.question': 'Risposta richiesta',
  'notification.questionBody': 'Harness ha posto una domanda e attende una risposta.',
  'notification.taskCompleted': 'Attività completata',
  'notification.taskCompletedBody': 'L’assistente ha completato l’attività corrente.',
  'notification.runtimeFailed': 'Harness si è arrestato in modo imprevisto',
  'notification.runtimeFailedBody': 'Apri Harness Desktop per le opzioni di ripristino.',
  'error.credentialEmpty': 'La chiave API non può essere vuota',
  'error.unknown': 'Si è verificato un errore',
  'inspector.toggle': 'Inspector',
  'inspector.files': 'File',
  'inspector.changes': 'Modifiche',
  'inspector.terminal': 'Terminale',
  'inspector.plan': 'Piano',
  'inspector.jobs': 'Processi',
  'inspector.subagents': 'Sub-agenti',
  'files.refresh': 'Aggiorna',
  'files.reveal': 'Mostra nel Finder',
  'files.empty': 'Nessun file',
  'files.searchPlaceholder': 'Cerca nel file…',
  'files.binary': 'Il file binario non può essere mostrato',
  'files.back': 'Indietro',
  'files.loadError': 'Impossibile caricare il file',
  'files.previewEmpty': 'Seleziona un file per l’anteprima',
  'changes.noRepo': 'Il workspace non è un repository Git',
  'changes.gitMissing': 'git non trovato',
  'changes.branch': 'Ramo',
  'changes.clean': 'Worktree pulito',
  'changes.filesCount': '{count} file modificati',
  'changes.added': 'Aggiunte',
  'changes.removed': 'Rimozioni',
  'changes.untracked': 'File non tracciati',
  'changes.empty': 'Nessuna modifica',
  'changes.staged': 'Modifiche in stage',
  'changes.stagedEmpty': 'Nessuna modifica in stage',
  'changes.changes': 'Modifiche',
  'changes.conflicted': 'Conflitti',
  'changes.stage': 'Stage',
  'changes.unstage': 'Unstage',
  'changes.staging': 'Staging…',
  'changes.unstaging': 'Unstaging…',
  'changes.dirtyStageWarning': 'Le modifiche non salvate nell’editor non sono incluse. Lo stage userà il file salvato su disco.',
  'changes.opFailed': 'Operazione Git non riuscita',
  'changes.outsideWorkspace': 'Fuori dal workspace',
  'changes.discard': 'Scarta modifiche',
  'changes.discardTitle': 'Scartare le modifiche?',
  'changes.discardConsequence': 'Questo ripristina il file salvato dal Git e non può essere annullato da Harness Desktop.',
  'changes.discardConsequenceStaged': 'Questo ripristina il file alla versione in stage. Le modifiche in stage restano.',
  'changes.discardBlockedDirty': 'Questo file ha modifiche non salvate. Salva o scarta la bozza dell’editor prima di scartare le modifiche dal disco.',
  'changes.discarding': 'Scarto…',
  'changes.stateChanged': 'Lo stato Git è cambiato. L’elenco è stato aggiornato; riprova.',
  'changes.cannotDiscard': 'Lo scarto non è disponibile per questo stato del file.',
  'changes.cancel': 'Annulla',
  'changes.unstaged': 'Non in stage',
  'changes.diffMode': 'Modalità diff',
  'changes.noStagedChanges': 'Nessuna modifica in stage',
  'changes.noUnstagedChanges': 'Nessuna modifica non in stage',
  'changes.binaryChanged': 'File binario modificato',
  'changes.diffTooLarge': 'Diff troppo grande da mostrare',
  'changes.prevFile': 'File precedente',
  'changes.nextFile': 'File successivo',
  'changes.openFile': 'Apri file',
  'changes.renameOnly': 'Solo rinomina — nessuna modifica al contenuto',
  'changes.diffSelectFile': 'Seleziona un file per vedere il suo diff',
  'changes.diffLoading': 'Caricamento diff…',
  'changes.untrackedNoDiff': 'File non tracciato — nessun diff Git disponibile',
  'changes.diffConflictReadOnly': 'lo stato di conflitto è di sola lettura',
  'terminal.noSession': 'Apri una sessione per usare il terminale',
  'terminal.new': 'Nuovo terminale',
  'terminal.close': 'Chiudi terminale',
  'terminal.inputHint': 'Scrivi qui e premi Invio',
  'terminal.exited': 'Processo terminato',
  'terminal.spawnError': 'Impossibile avviare il terminale',
  'plan.empty': 'Nessun piano strutturato',
  'plan.pending': 'In attesa',
  'plan.active': 'Attivo',
  'plan.completed': 'Completato',
  'jobs.empty': 'Nessun processo in background',
  'jobs.killed': 'Terminato',
  'jobs.failed': 'Fallito',
  'jobs.stopped': 'Fermato',
  'subagents.empty': 'Nessun sub-agente',
  'subagents.main': 'Agente principale',
  'subagents.running': 'In esecuzione',
  'subagents.completed': 'Completato',
  'editor.backToConversation': 'Torna alla conversazione',
  'editor.empty': 'Nessun file aperto',
  'editor.save': 'Salva',
  'editor.saving': 'Salvataggio…',
  'editor.saved': 'Salvato',
  'editor.dirty': 'Modifiche non salvate',
  'editor.saveError': 'Salvataggio non riuscito',
  'editor.conflictState': 'Conflitto',
  'editor.conflictBody': 'Il file è cambiato su disco dopo l’apertura. Ricarica per vedere il contenuto più recente, oppure continua a modificare.',
  'editor.conflictReload': 'Ricarica dal disco',
  'editor.conflictKeep': 'Continua a modificare',
  'editor.closeTab': 'Chiudi scheda',
  'editor.unsavedBody': 'Questo file ha modifiche non salvate.',
  'editor.unsavedCancel': 'Annulla',
  'editor.unsavedDiscard': 'Scarta le modifiche',
  'editor.unsavedSave': 'Salva',
  'editor.readOnly': 'Sola lettura',
  'editor.large': 'File troppo grande per la modifica',
  'editor.externalState': 'Modificato esternamente',
  'editor.externalBody': 'Questo file è cambiato su disco. Le tue modifiche restano in memoria.',
  'editor.externalReload': 'Rivedi / Ricarica',
  'editor.externalKeep': 'Mantieni le mie modifiche',
  'editor.deletedState': 'Eliminato',
  'editor.deletedBody': 'Questo file è stato eliminato su disco. La scheda conserva il contenuto; nulla viene ricreato automaticamente.',
  'editor.deletedClose': 'Chiudi scheda',
  'editor.saveAll': 'Salva tutto',
  'quickOpen.placeholder': 'Cerca file…',
  'quickOpen.indexing': 'Indicizzazione workspace…',
  'quickOpen.empty': 'Nessun file in questo workspace',
  'quickOpen.noMatch': 'Nessun file corrispondente',
  'quickOpen.hint': '↑ ↓ naviga · Invio apre · Esc chiude',
  'quitGuard.title': 'Modifiche non salvate',
  'quitGuard.body': 'Alcuni file hanno modifiche non salvate. Uscire ora?',
  'quitGuard.cancel': 'Annulla',
  'quitGuard.discard': 'Scarta ed esci',
  'quitGuard.saveAll': 'Salva tutto ed esci',
  'quitGuard.saveFailed': 'Alcuni file non sono stati salvati (versione non aggiornata). Nulla è stato scartato.',
}

/** Chinese dictionary, complete against the English key set. */
export const zh: Record<DesktopStringKey, string> = {
  'onboarding.welcome.title': '欢迎使用 Harness Desktop',
  'onboarding.welcome.body': '基于 DeepSeek Harness 的 AI 编程。非官方桌面客户端。',
  'onboarding.welcome.continue': '继续',
  'onboarding.provider.title': '连接 DeepSeek',
  'onboarding.provider.apiKey': 'API 密钥',
  'onboarding.provider.baseUrl': 'Base URL（可选）',
  'onboarding.provider.save': '保存到钥匙串',
  'onboarding.back': '返回',
  'onboarding.workspace.title': '选择项目',
  'onboarding.workspace.body': '选择 Harness 的工作目录。接下来会打开 macOS 原生文件夹选择器。',
  'onboarding.workspace.pick': '打开文件夹选择器',
  'status.starting': '正在启动 Harness…',
  'status.running': '已连接',
  'status.restarting': '正在重启 Harness…',
  'status.stopped': 'Harness 已停止',
  'status.failed': 'Harness 不可用',
  'status.stopping': '正在停止 Harness…',
  'failure.title': 'Harness 意外停止。',
  'failure.restart': '重启 Harness',
  'failure.logs': '打开日志',
  'settings.language': '语言',
  'settings.language.system': '跟随系统',
  'settings.language.english': 'English',
  'settings.language.italian': 'Italiano',
  'settings.language.chinese': '中文',
  'settings.language.spanish': 'Español',
  'settings.language.french': 'Français',
  'settings.language.german': 'Deutsch',
  'settings.language.portuguese': 'Português (Brasil)',
  'settings.advanced': '高级',
  'settings.desktopVersion': '桌面版本',
  'settings.harnessVersion': 'Harness 版本',
  'settings.protocol': '桌面协议',
  'settings.runtimeState': '运行时状态',
  'settings.restart': '重启 Harness',
  'settings.logs': '打开日志',
  'settings.diagnostics': '复制诊断信息',
  'settings.title': '设置',
  'settings.close': '关闭',
  'credentials.title': 'DeepSeek 凭据',
  'credentials.configured': 'API 密钥已保存在 macOS 钥匙串中。',
  'credentials.notConfigured': '尚未配置 API 密钥。',
  'credentials.replace': '更换 API 密钥',
  'credentials.replacePlaceholder': '新 API 密钥',
  'credentials.replaceSave': '保存',
  'credentials.remove': '删除 API 密钥',
  'credentials.removeConfirm': '删除已保存的 API 密钥？在保存新密钥之前，助手将无法进行身份验证。',
  'credentials.removeConfirmYes': '删除',
  'credentials.removeConfirmNo': '取消',
  'settings.baseUrl': 'Base URL',
  'settings.baseUrlPlaceholder': 'https://api.deepseek.com',
  'settings.baseUrlSave': '保存',
  'settings.baseUrlInvalid': 'Base URL 必须以 https:// 开头',
  'settings.copy': '复制',
  'notification.approval': '需要批准',
  'notification.approvalBody': 'Harness 正在等待权限决定。',
  'notification.question': '需要输入',
  'notification.questionBody': 'Harness 提出了一个问题，正在等待回答。',
  'notification.taskCompleted': '任务已完成',
  'notification.taskCompletedBody': '助手已完成当前任务。',
  'notification.runtimeFailed': 'Harness 意外停止',
  'notification.runtimeFailedBody': '打开 Harness Desktop 查看恢复选项。',
  'error.credentialEmpty': 'API 密钥不能为空',
  'error.unknown': '出了点问题',
  'inspector.toggle': '检查器',
  'inspector.files': '文件',
  'inspector.changes': '更改',
  'inspector.terminal': '终端',
  'inspector.plan': '计划',
  'inspector.jobs': '任务',
  'inspector.subagents': '子代理',
  'files.refresh': '刷新',
  'files.reveal': '在 Finder 中显示',
  'files.empty': '暂无文件',
  'files.searchPlaceholder': '在文件中搜索…',
  'files.binary': '二进制文件无法预览',
  'files.back': '返回',
  'files.loadError': '无法加载文件',
  'files.previewEmpty': '选择一个文件进行预览',
  'changes.noRepo': '当前工作区不是 Git 仓库',
  'changes.gitMissing': '未找到 git',
  'changes.branch': '分支',
  'changes.clean': '工作区干净',
  'changes.filesCount': '{count} 个已更改文件',
  'changes.added': '新增',
  'changes.removed': '删除',
  'changes.untracked': '未跟踪文件',
  'changes.empty': '没有更改',
  'changes.staged': '暂存更改',
  'changes.stagedEmpty': '没有暂存的更改',
  'changes.changes': '更改',
  'changes.conflicted': '冲突',
  'changes.stage': '暂存',
  'changes.unstage': '取消暂存',
  'changes.staging': '暂存中…',
  'changes.unstaging': '取消暂存中…',
  'changes.dirtyStageWarning': '编辑器未保存的更改不会包含在内。暂存将使用磁盘上已保存的文件。',
  'changes.opFailed': 'Git 操作失败',
  'changes.outsideWorkspace': '工作区之外',
  'changes.discard': '放弃更改',
  'changes.discardTitle': '放弃更改？',
  'changes.discardConsequence': '这将从 Git 恢复已保存的工作区文件，且 Harness Desktop 无法撤销。',
  'changes.discardConsequenceStaged': '这将把工作区文件恢复到已暂存版本。暂存的更改仍然保留。',
  'changes.discardBlockedDirty': '此文件有未保存的编辑器更改。请先保存或放弃编辑器草稿，再放弃磁盘上的更改。',
  'changes.discarding': '放弃中…',
  'changes.stateChanged': 'Git 状态已更改。文件列表已刷新；请重试。',
  'changes.cannotDiscard': '此文件状态不支持放弃。',
  'changes.cancel': '取消',
  'changes.unstaged': '未暂存',
  'changes.diffMode': 'Diff 模式',
  'changes.noStagedChanges': '没有暂存的更改',
  'changes.noUnstagedChanges': '没有未暂存的更改',
  'changes.binaryChanged': '二进制文件已更改',
  'changes.diffTooLarge': 'Diff 太大，无法显示',
  'changes.prevFile': '上一个文件',
  'changes.nextFile': '下一个文件',
  'changes.openFile': '打开文件',
  'changes.renameOnly': '仅重命名 — 无内容更改',
  'changes.diffSelectFile': '选择一个文件以查看其 diff',
  'changes.diffLoading': '正在加载 diff…',
  'changes.untrackedNoDiff': '未跟踪文件 — 没有可用的 Git diff',
  'changes.diffConflictReadOnly': '冲突状态为只读',
  'terminal.noSession': '打开一个会话以使用终端',
  'terminal.new': '新建终端',
  'terminal.close': '关闭终端',
  'terminal.inputHint': '在此输入并按回车执行',
  'terminal.exited': '进程已退出',
  'terminal.spawnError': '无法启动终端',
  'plan.empty': '暂无结构化计划',
  'plan.pending': '待处理',
  'plan.active': '进行中',
  'plan.completed': '已完成',
  'jobs.empty': '无后台任务',
  'jobs.killed': '已终止',
  'jobs.failed': '失败',
  'jobs.stopped': '已停止',
  'subagents.empty': '暂无子代理',
  'subagents.main': '主代理',
  'subagents.running': '运行中',
  'subagents.completed': '已完成',
  'editor.backToConversation': '返回对话',
  'editor.empty': '没有打开的文件',
  'editor.save': '保存',
  'editor.saving': '保存中…',
  'editor.saved': '已保存',
  'editor.dirty': '未保存的更改',
  'editor.saveError': '保存失败',
  'editor.conflictState': '冲突',
  'editor.conflictBody': '文件在打开后已在磁盘上发生变化。重新加载以查看较新的内容，或继续编辑。',
  'editor.conflictReload': '从磁盘重新加载',
  'editor.conflictKeep': '继续编辑',
  'editor.closeTab': '关闭标签页',
  'editor.unsavedBody': '此文件有未保存的更改。',
  'editor.unsavedCancel': '取消',
  'editor.unsavedDiscard': '放弃更改',
  'editor.unsavedSave': '保存',
  'editor.readOnly': '只读',
  'editor.large': '文件太大，无法编辑',
  'editor.externalState': '外部已修改',
  'editor.externalBody': '此文件已在磁盘上更改。你的编辑仍保留在内存中。',
  'editor.externalReload': '查看 / 重新加载',
  'editor.externalKeep': '保留我的更改',
  'editor.deletedState': '已删除',
  'editor.deletedBody': '此文件已在磁盘上删除。标签页保留内容；不会自动重新创建。',
  'editor.deletedClose': '关闭标签页',
  'editor.saveAll': '全部保存',
  'quickOpen.placeholder': '搜索文件…',
  'quickOpen.indexing': '正在索引工作区…',
  'quickOpen.empty': '此工作区没有文件',
  'quickOpen.noMatch': '没有匹配的文件',
  'quickOpen.hint': '↑ ↓ 导航 · 回车打开 · Esc 关闭',
  'quitGuard.title': '未保存的更改',
  'quitGuard.body': '部分文件有未保存的更改。现在退出？',
  'quitGuard.cancel': '取消',
  'quitGuard.discard': '放弃并退出',
  'quitGuard.saveAll': '全部保存并退出',
  'quitGuard.saveFailed': '部分文件无法保存（版本已过期）。未丢弃任何内容。',
}
/** Spanish dictionary, complete against the English key set. */
export const es: Record<DesktopStringKey, string> = {
  'onboarding.welcome.title': 'Bienvenido a Harness Desktop',
  'onboarding.welcome.body': 'Programación con IA basada en DeepSeek Harness. Cliente de escritorio no oficial.',
  'onboarding.welcome.continue': 'Continuar',
  'onboarding.provider.title': 'Conectar DeepSeek',
  'onboarding.provider.apiKey': 'Clave de API',
  'onboarding.provider.baseUrl': 'URL base (opcional)',
  'onboarding.provider.save': 'Guardar en el llavero',
  'onboarding.back': 'Atrás',
  'onboarding.workspace.title': 'Elige un proyecto',
  'onboarding.workspace.body': 'Selecciona la carpeta en la que trabajará Harness. Se abrirá el selector nativo de macOS.',
  'onboarding.workspace.pick': 'Abrir selector de carpeta',
  'status.starting': 'Iniciando Harness…',
  'status.running': 'Conectado',
  'status.restarting': 'Reiniciando Harness…',
  'status.stopped': 'Harness detenido',
  'status.failed': 'Harness no disponible',
  'status.stopping': 'Deteniendo Harness…',
  'failure.title': 'Harness se detuvo inesperadamente.',
  'failure.restart': 'Reiniciar Harness',
  'failure.logs': 'Abrir registros',
  'settings.language': 'Idioma',
  'settings.language.system': 'Sistema',
  'settings.language.english': 'English',
  'settings.language.italian': 'Italiano',
  'settings.language.chinese': 'Chino',
  'settings.language.spanish': 'Español',
  'settings.language.french': 'Francés',
  'settings.language.german': 'Alemán',
  'settings.language.portuguese': 'Portugués (Brasil)',
  'settings.advanced': 'Avanzado',
  'settings.desktopVersion': 'Versión de escritorio',
  'settings.harnessVersion': 'Versión de Harness',
  'settings.protocol': 'Protocolo de escritorio',
  'settings.runtimeState': 'Estado del tiempo de ejecución',
  'settings.restart': 'Reiniciar Harness',
  'settings.logs': 'Abrir registros',
  'settings.diagnostics': 'Copiar diagnóstico',
  'settings.title': 'Ajustes',
  'settings.close': 'Cerrar',
  'credentials.title': 'Credenciales de DeepSeek',
  'credentials.configured': 'Clave de API guardada en el llavero de macOS.',
  'credentials.notConfigured': 'No hay ninguna clave de API configurada.',
  'credentials.replace': 'Reemplazar clave de API',
  'credentials.replacePlaceholder': 'Nueva clave de API',
  'credentials.replaceSave': 'Guardar',
  'credentials.remove': 'Eliminar clave de API',
  'credentials.removeConfirm': '¿Eliminar la clave de API guardada? El asistente dejará de autenticarse hasta que se guarde una nueva clave.',
  'credentials.removeConfirmYes': 'Eliminar',
  'credentials.removeConfirmNo': 'Cancelar',
  'settings.baseUrl': 'URL base',
  'settings.baseUrlPlaceholder': 'https://api.deepseek.com',
  'settings.baseUrlSave': 'Guardar',
  'settings.baseUrlInvalid': 'La URL base debe usar https://',
  'settings.copy': 'Copiar',
  'notification.approval': 'Aprobación requerida',
  'notification.approvalBody': 'Harness espera una decisión de permisos.',
  'notification.question': 'Se requiere una respuesta',
  'notification.questionBody': 'Harness hizo una pregunta y espera una respuesta.',
  'notification.taskCompleted': 'Tarea completada',
  'notification.taskCompletedBody': 'El asistente terminó la tarea actual.',
  'notification.runtimeFailed': 'Harness se detuvo inesperadamente',
  'notification.runtimeFailedBody': 'Abre Harness Desktop para ver las opciones de recuperación.',
  'error.credentialEmpty': 'La clave de API no puede estar vacía',
  'error.unknown': 'Algo salió mal',
  'inspector.toggle': 'Inspector',
  'inspector.files': 'Archivos',
  'inspector.changes': 'Cambios',
  'inspector.terminal': 'Terminal',
  'inspector.plan': 'Plan',
  'inspector.jobs': 'Tareas',
  'inspector.subagents': 'Subagentes',
  'files.refresh': 'Actualizar',
  'files.reveal': 'Mostrar en el Finder',
  'files.empty': 'Sin archivos',
  'files.searchPlaceholder': 'Buscar en el archivo…',
  'files.binary': 'El archivo binario no se puede mostrar',
  'files.back': 'Atrás',
  'files.loadError': 'No se pudo cargar el archivo',
  'files.previewEmpty': 'Selecciona un archivo para previsualizar',
  'changes.noRepo': 'El espacio de trabajo no es un repositorio Git',
  'changes.gitMissing': 'No se encontró git',
  'changes.branch': 'Rama',
  'changes.clean': 'Árbol de trabajo limpio',
  'changes.filesCount': '{count} archivos modificados',
  'changes.added': 'Adiciones',
  'changes.removed': 'Eliminaciones',
  'changes.untracked': 'Archivos sin seguimiento',
  'changes.empty': 'Sin cambios',
  'changes.staged': 'Cambios en preparación',
  'changes.stagedEmpty': 'Nada en preparación',
  'changes.changes': 'Cambios',
  'changes.conflicted': 'Conflictos',
  'changes.stage': 'Preparar',
  'changes.unstage': 'Quitar de preparación',
  'changes.staging': 'Preparando…',
  'changes.unstaging': 'Quitando de preparación…',
  'changes.dirtyStageWarning': 'Los cambios sin guardar del editor no se incluyen. La preparación usará el archivo guardado en disco.',
  'changes.opFailed': 'Falló la operación de Git',
  'changes.outsideWorkspace': 'Fuera del espacio de trabajo',
  'changes.discard': 'Descartar cambios',
  'changes.discardTitle': '¿Descartar los cambios?',
  'changes.discardConsequence': 'Esto restaura el archivo guardado desde Git y Harness Desktop no puede deshacerlo.',
  'changes.discardConsequenceStaged': 'Esto restaura el archivo a la versión preparada. Los cambios preparados permanecen.',
  'changes.discardBlockedDirty': 'Este archivo tiene cambios sin guardar. Guarda o descarta el borrador del editor antes de descartar los cambios del disco.',
  'changes.discarding': 'Descartando…',
  'changes.stateChanged': 'El estado de Git cambió. La lista se actualizó; inténtalo de nuevo.',
  'changes.cannotDiscard': 'Descartar no está disponible para este estado del archivo.',
  'changes.cancel': 'Cancelar',
  'changes.unstaged': 'Sin preparar',
  'changes.diffMode': 'Modo de diff',
  'changes.noStagedChanges': 'No hay cambios preparados',
  'changes.noUnstagedChanges': 'No hay cambios sin preparar',
  'changes.binaryChanged': 'Archivo binario modificado',
  'changes.diffTooLarge': 'Diff demasiado grande para mostrar',
  'changes.prevFile': 'Archivo anterior',
  'changes.nextFile': 'Archivo siguiente',
  'changes.openFile': 'Abrir archivo',
  'changes.renameOnly': 'Solo renombrado — sin cambios de contenido',
  'changes.diffSelectFile': 'Selecciona un archivo para ver su diff',
  'changes.diffLoading': 'Cargando diff…',
  'changes.untrackedNoDiff': 'Archivo sin seguimiento — no hay diff de Git disponible',
  'changes.diffConflictReadOnly': 'el estado de conflicto es de solo lectura',
  'terminal.noSession': 'Abre una sesión para usar el terminal',
  'terminal.new': 'Nuevo terminal',
  'terminal.close': 'Cerrar terminal',
  'terminal.inputHint': 'Escribe aquí y pulsa Intro',
  'terminal.exited': 'Proceso finalizado',
  'terminal.spawnError': 'No se pudo iniciar el terminal',
  'plan.empty': 'Sin plan estructurado',
  'plan.pending': 'Pendiente',
  'plan.active': 'Activo',
  'plan.completed': 'Completado',
  'jobs.empty': 'Sin tareas en segundo plano',
  'jobs.killed': 'Terminada',
  'jobs.failed': 'Fallida',
  'jobs.stopped': 'Detenida',
  'subagents.empty': 'Sin subagentes',
  'subagents.main': 'Agente principal',
  'subagents.running': 'En ejecución',
  'subagents.completed': 'Completado',
  'editor.backToConversation': 'Volver a la conversación',
  'editor.empty': 'No hay archivos abiertos',
  'editor.save': 'Guardar',
  'editor.saving': 'Guardando…',
  'editor.saved': 'Guardado',
  'editor.dirty': 'Cambios sin guardar',
  'editor.saveError': 'Error al guardar',
  'editor.conflictState': 'Conflicto',
  'editor.conflictBody': 'El archivo cambió en el disco desde que se abrió. Recarga para ver el contenido más reciente o sigue editando.',
  'editor.conflictReload': 'Recargar del disco',
  'editor.conflictKeep': 'Seguir editando',
  'editor.closeTab': 'Cerrar pestaña',
  'editor.unsavedBody': 'Este archivo tiene cambios sin guardar.',
  'editor.unsavedCancel': 'Cancelar',
  'editor.unsavedDiscard': 'Descartar cambios',
  'editor.unsavedSave': 'Guardar',
  'editor.readOnly': 'Solo lectura',
  'editor.large': 'Archivo demasiado grande para editar',
  'editor.externalState': 'Cambiado externamente',
  'editor.externalBody': 'Este archivo cambió en el disco. Tus ediciones se conservan en memoria.',
  'editor.externalReload': 'Revisar / Recargar',
  'editor.externalKeep': 'Conservar mis cambios',
  'editor.deletedState': 'Eliminado',
  'editor.deletedBody': 'Este archivo fue eliminado del disco. La pestaña conserva el contenido; no se recrea nada automáticamente.',
  'editor.deletedClose': 'Cerrar pestaña',
  'editor.saveAll': 'Guardar todo',
  'quickOpen.placeholder': 'Buscar archivos…',
  'quickOpen.indexing': 'Indexando el workspace…',
  'quickOpen.empty': 'No hay archivos en este workspace',
  'quickOpen.noMatch': 'No hay archivos que coincidan',
  'quickOpen.hint': '↑ ↓ navegar · Enter abre · Esc cierra',
  'quitGuard.title': 'Cambios sin guardar',
  'quitGuard.body': 'Algunos archivos tienen cambios sin guardar. ¿Salir ahora?',
  'quitGuard.cancel': 'Cancelar',
  'quitGuard.discard': 'Descartar y salir',
  'quitGuard.saveAll': 'Guardar todo y salir',
  'quitGuard.saveFailed': 'No se pudieron guardar algunos archivos (versión obsoleta). No se descartó nada.',
}
/** French dictionary, complete against the English key set. */
export const fr: Record<DesktopStringKey, string> = {
  'onboarding.welcome.title': 'Bienvenue dans Harness Desktop',
  'onboarding.welcome.body': 'Programmation assistée par IA avec DeepSeek Harness. Client de bureau non officiel.',
  'onboarding.welcome.continue': 'Continuer',
  'onboarding.provider.title': 'Connecter DeepSeek',
  'onboarding.provider.apiKey': 'Clé API',
  'onboarding.provider.baseUrl': 'URL de base (facultatif)',
  'onboarding.provider.save': 'Enregistrer dans le trousseau',
  'onboarding.back': 'Retour',
  'onboarding.workspace.title': 'Choisir un projet',
  'onboarding.workspace.body': 'Sélectionnez le dossier dans lequel Harness travaillera. Le sélecteur natif de macOS s’ouvre ensuite.',
  'onboarding.workspace.pick': 'Ouvrir le sélecteur de dossier',
  'status.starting': 'Démarrage de Harness…',
  'status.running': 'Connecté',
  'status.restarting': 'Redémarrage de Harness…',
  'status.stopped': 'Harness arrêté',
  'status.failed': 'Harness indisponible',
  'status.stopping': 'Arrêt de Harness…',
  'failure.title': 'Harness s’est arrêté de manière inattendue.',
  'failure.restart': 'Redémarrer Harness',
  'failure.logs': 'Ouvrir les journaux',
  'settings.language': 'Langue',
  'settings.language.system': 'Système',
  'settings.language.english': 'English',
  'settings.language.italian': 'Italiano',
  'settings.language.chinese': 'Chinois',
  'settings.language.spanish': 'Espagnol',
  'settings.language.french': 'Français',
  'settings.language.german': 'Allemand',
  'settings.language.portuguese': 'Portugais (Brésil)',
  'settings.advanced': 'Avancé',
  'settings.desktopVersion': 'Version du bureau',
  'settings.harnessVersion': 'Version de Harness',
  'settings.protocol': 'Protocole du bureau',
  'settings.runtimeState': 'État du moteur d’exécution',
  'settings.restart': 'Redémarrer Harness',
  'settings.logs': 'Ouvrir les journaux',
  'settings.diagnostics': 'Copier le diagnostic',
  'settings.title': 'Réglages',
  'settings.close': 'Fermer',
  'credentials.title': 'Identifiants DeepSeek',
  'credentials.configured': 'Clé API enregistrée dans le trousseau de macOS.',
  'credentials.notConfigured': 'Aucune clé API configurée.',
  'credentials.replace': 'Remplacer la clé API',
  'credentials.replacePlaceholder': 'Nouvelle clé API',
  'credentials.replaceSave': 'Enregistrer',
  'credentials.remove': 'Supprimer la clé API',
  'credentials.removeConfirm': 'Supprimer la clé API enregistrée ? L’assistant cessera de s’authentifier jusqu’à l’enregistrement d’une nouvelle clé.',
  'credentials.removeConfirmYes': 'Supprimer',
  'credentials.removeConfirmNo': 'Annuler',
  'settings.baseUrl': 'URL de base',
  'settings.baseUrlPlaceholder': 'https://api.deepseek.com',
  'settings.baseUrlSave': 'Enregistrer',
  'settings.baseUrlInvalid': 'L’URL de base doit utiliser https://',
  'settings.copy': 'Copier',
  'notification.approval': 'Approbation requise',
  'notification.approvalBody': 'Harness attend une décision concernant les autorisations.',
  'notification.question': 'Réponse requise',
  'notification.questionBody': 'Harness a posé une question et attend une réponse.',
  'notification.taskCompleted': 'Tâche terminée',
  'notification.taskCompletedBody': 'L’assistant a terminé la tâche en cours.',
  'notification.runtimeFailed': 'Harness s’est arrêté de manière inattendue',
  'notification.runtimeFailedBody': 'Ouvrez Harness Desktop pour les options de récupération.',
  'error.credentialEmpty': 'La clé API ne peut pas être vide',
  'error.unknown': 'Une erreur est survenue',
  'inspector.toggle': 'Inspecteur',
  'inspector.files': 'Fichiers',
  'inspector.changes': 'Modifications',
  'inspector.terminal': 'Terminal',
  'inspector.plan': 'Plan',
  'inspector.jobs': 'Tâches',
  'inspector.subagents': 'Sous-agents',
  'files.refresh': 'Actualiser',
  'files.reveal': 'Afficher dans le Finder',
  'files.empty': 'Aucun fichier',
  'files.searchPlaceholder': 'Rechercher dans le fichier…',
  'files.binary': 'Le fichier binaire ne peut pas être affiché',
  'files.back': 'Retour',
  'files.loadError': 'Impossible de charger le fichier',
  'files.previewEmpty': 'Sélectionnez un fichier pour l’aperçu',
  'changes.noRepo': 'L’espace de travail n’est pas un dépôt Git',
  'changes.gitMissing': 'git introuvable',
  'changes.branch': 'Branche',
  'changes.clean': 'Arbre de travail propre',
  'changes.filesCount': '{count} fichiers modifiés',
  'changes.added': 'Ajouts',
  'changes.removed': 'Suppressions',
  'changes.untracked': 'Fichiers non suivis',
  'changes.empty': 'Aucune modification',
  'changes.staged': 'Modifications indexées',
  'changes.stagedEmpty': 'Aucune modification indexée',
  'changes.changes': 'Modifications',
  'changes.conflicted': 'Conflits',
  'changes.stage': 'Indexer',
  'changes.unstage': 'Désindexer',
  'changes.staging': 'Indexation…',
  'changes.unstaging': 'Désindexation…',
  'changes.dirtyStageWarning': 'Les modifications non enregistrées de l’éditeur ne sont pas incluses. L’indexation utilisera le fichier enregistré sur le disque.',
  'changes.opFailed': 'Échec de l’opération Git',
  'changes.outsideWorkspace': 'Hors de l’espace de travail',
  'changes.discard': 'Abandonner les modifications',
  'changes.discardTitle': 'Abandonner les modifications ?',
  'changes.discardConsequence': 'Cela restaure le fichier enregistré depuis Git et Harness Desktop ne peut pas l’annuler.',
  'changes.discardConsequenceStaged': 'Cela restaure le fichier à la version indexée. Les modifications indexées restent.',
  'changes.discardBlockedDirty': 'Ce fichier contient des modifications non enregistrées. Enregistrez ou abandonnez le brouillon de l’éditeur avant d’abandonner les modifications du disque.',
  'changes.discarding': 'Abandon…',
  'changes.stateChanged': 'L’état de Git a changé. La liste a été actualisée ; réessayez.',
  'changes.cannotDiscard': 'L’abandon n’est pas disponible pour cet état du fichier.',
  'changes.cancel': 'Annuler',
  'changes.unstaged': 'Non indexé',
  'changes.diffMode': 'Mode de diff',
  'changes.noStagedChanges': 'Aucune modification indexée',
  'changes.noUnstagedChanges': 'Aucune modification non indexée',
  'changes.binaryChanged': 'Fichier binaire modifié',
  'changes.diffTooLarge': 'Diff trop volumineux pour être affiché',
  'changes.prevFile': 'Fichier précédent',
  'changes.nextFile': 'Fichier suivant',
  'changes.openFile': 'Ouvrir le fichier',
  'changes.renameOnly': 'Renommage uniquement — aucun changement de contenu',
  'changes.diffSelectFile': 'Sélectionnez un fichier pour voir son diff',
  'changes.diffLoading': 'Chargement du diff…',
  'changes.untrackedNoDiff': 'Fichier non suivi — aucun diff Git disponible',
  'changes.diffConflictReadOnly': 'l’état de conflit est en lecture seule',
  'terminal.noSession': 'Ouvrez une session pour utiliser le terminal',
  'terminal.new': 'Nouveau terminal',
  'terminal.close': 'Fermer le terminal',
  'terminal.inputHint': 'Saisissez ici et appuyez sur Entrée',
  'terminal.exited': 'Processus terminé',
  'terminal.spawnError': 'Impossible de démarrer le terminal',
  'plan.empty': 'Aucun plan structuré',
  'plan.pending': 'En attente',
  'plan.active': 'Actif',
  'plan.completed': 'Terminé',
  'jobs.empty': 'Aucune tâche en arrière-plan',
  'jobs.killed': 'Arrêtée',
  'jobs.failed': 'Échouée',
  'jobs.stopped': 'Stoppée',
  'subagents.empty': 'Aucun sous-agent',
  'subagents.main': 'Agent principal',
  'subagents.running': 'En cours',
  'subagents.completed': 'Terminé',
  'editor.backToConversation': 'Retour à la conversation',
  'editor.empty': 'Aucun fichier ouvert',
  'editor.save': 'Enregistrer',
  'editor.saving': 'Enregistrement…',
  'editor.saved': 'Enregistré',
  'editor.dirty': 'Modifications non enregistrées',
  'editor.saveError': 'Échec de l’enregistrement',
  'editor.conflictState': 'Conflit',
  'editor.conflictBody': 'Le fichier a changé sur le disque depuis son ouverture. Rechargez pour voir le contenu le plus récent, ou continuez à modifier.',
  'editor.conflictReload': 'Recharger depuis le disque',
  'editor.conflictKeep': 'Continuer à modifier',
  'editor.closeTab': 'Fermer l’onglet',
  'editor.unsavedBody': 'Ce fichier a des modifications non enregistrées.',
  'editor.unsavedCancel': 'Annuler',
  'editor.unsavedDiscard': 'Abandonner les modifications',
  'editor.unsavedSave': 'Enregistrer',
  'editor.readOnly': 'Lecture seule',
  'editor.large': 'Fichier trop volumineux pour la modification',
  'editor.externalState': 'Modifié en externe',
  'editor.externalBody': 'Ce fichier a changé sur le disque. Vos modifications restent en mémoire.',
  'editor.externalReload': 'Réviser / Recharger',
  'editor.externalKeep': 'Conserver mes modifications',
  'editor.deletedState': 'Supprimé',
  'editor.deletedBody': 'Ce fichier a été supprimé du disque. L’onglet conserve son contenu ; rien n’est recréé automatiquement.',
  'editor.deletedClose': 'Fermer l’onglet',
  'editor.saveAll': 'Tout enregistrer',
  'quickOpen.placeholder': 'Rechercher des fichiers…',
  'quickOpen.indexing': 'Indexation du workspace…',
  'quickOpen.empty': 'Aucun fichier dans ce workspace',
  'quickOpen.noMatch': 'Aucun fichier correspondant',
  'quickOpen.hint': '↑ ↓ naviguer · Entrée ouvre · Échap ferme',
  'quitGuard.title': 'Modifications non enregistrées',
  'quitGuard.body': 'Certains fichiers ont des modifications non enregistrées. Quitter maintenant ?',
  'quitGuard.cancel': 'Annuler',
  'quitGuard.discard': 'Ignorer et quitter',
  'quitGuard.saveAll': 'Tout enregistrer et quitter',
  'quitGuard.saveFailed': 'Certains fichiers n’ont pas pu être enregistrés (version obsolète). Rien n’a été ignoré.',
}
/** German dictionary, complete against the English key set. */
export const de: Record<DesktopStringKey, string> = {
  'onboarding.welcome.title': 'Willkommen bei Harness Desktop',
  'onboarding.welcome.body': 'KI-gestütztes Programmieren mit DeepSeek Harness. Inoffizieller Desktop-Client.',
  'onboarding.welcome.continue': 'Weiter',
  'onboarding.provider.title': 'DeepSeek verbinden',
  'onboarding.provider.apiKey': 'API-Schlüssel',
  'onboarding.provider.baseUrl': 'Basis-URL (optional)',
  'onboarding.provider.save': 'Im Schlüsselbund speichern',
  'onboarding.back': 'Zurück',
  'onboarding.workspace.title': 'Projekt auswählen',
  'onboarding.workspace.body': 'Wählen Sie den Ordner, in dem Harness arbeiten soll. Als Nächstes öffnet sich die native macOS-Auswahl.',
  'onboarding.workspace.pick': 'Ordnerauswahl öffnen',
  'status.starting': 'Harness wird gestartet…',
  'status.running': 'Verbunden',
  'status.restarting': 'Harness wird neu gestartet…',
  'status.stopped': 'Harness angehalten',
  'status.failed': 'Harness nicht verfügbar',
  'status.stopping': 'Harness wird angehalten…',
  'failure.title': 'Harness wurde unerwartet beendet.',
  'failure.restart': 'Harness neu starten',
  'failure.logs': 'Protokolle öffnen',
  'settings.language': 'Sprache',
  'settings.language.system': 'System',
  'settings.language.english': 'English',
  'settings.language.italian': 'Italienisch',
  'settings.language.chinese': 'Chinesisch',
  'settings.language.spanish': 'Spanisch',
  'settings.language.french': 'Französisch',
  'settings.language.german': 'Deutsch',
  'settings.language.portuguese': 'Portugiesisch (Brasilien)',
  'settings.advanced': 'Erweitert',
  'settings.desktopVersion': 'Desktop-Version',
  'settings.harnessVersion': 'Harness-Version',
  'settings.protocol': 'Desktop-Protokoll',
  'settings.runtimeState': 'Laufzeitstatus',
  'settings.restart': 'Harness neu starten',
  'settings.logs': 'Protokolle öffnen',
  'settings.diagnostics': 'Diagnose kopieren',
  'settings.title': 'Einstellungen',
  'settings.close': 'Schließen',
  'credentials.title': 'DeepSeek-Anmeldedaten',
  'credentials.configured': 'API-Schlüssel im macOS-Schlüsselbund gespeichert.',
  'credentials.notConfigured': 'Kein API-Schlüssel konfiguriert.',
  'credentials.replace': 'API-Schlüssel ersetzen',
  'credentials.replacePlaceholder': 'Neuer API-Schlüssel',
  'credentials.replaceSave': 'Speichern',
  'credentials.remove': 'API-Schlüssel entfernen',
  'credentials.removeConfirm': 'Gespeicherten API-Schlüssel entfernen? Der Assistent kann sich erst wieder authentifizieren, wenn ein neuer Schlüssel gespeichert wurde.',
  'credentials.removeConfirmYes': 'Entfernen',
  'credentials.removeConfirmNo': 'Abbrechen',
  'settings.baseUrl': 'Basis-URL',
  'settings.baseUrlPlaceholder': 'https://api.deepseek.com',
  'settings.baseUrlSave': 'Speichern',
  'settings.baseUrlInvalid': 'Die Basis-URL muss https:// verwenden',
  'settings.copy': 'Kopieren',
  'notification.approval': 'Genehmigung erforderlich',
  'notification.approvalBody': 'Harness wartet auf eine Berechtigungsentscheidung.',
  'notification.question': 'Eingabe erforderlich',
  'notification.questionBody': 'Harness hat eine Frage gestellt und wartet auf eine Antwort.',
  'notification.taskCompleted': 'Aufgabe abgeschlossen',
  'notification.taskCompletedBody': 'Der Assistent hat die aktuelle Aufgabe abgeschlossen.',
  'notification.runtimeFailed': 'Harness wurde unerwartet beendet',
  'notification.runtimeFailedBody': 'Öffnen Sie Harness Desktop für Wiederherstellungsoptionen.',
  'error.credentialEmpty': 'Der API-Schlüssel darf nicht leer sein',
  'error.unknown': 'Etwas ist schiefgelaufen',
  'inspector.toggle': 'Inspektor',
  'inspector.files': 'Dateien',
  'inspector.changes': 'Änderungen',
  'inspector.terminal': 'Terminal',
  'inspector.plan': 'Plan',
  'inspector.jobs': 'Aufträge',
  'inspector.subagents': 'Subagenten',
  'files.refresh': 'Aktualisieren',
  'files.reveal': 'Im Finder anzeigen',
  'files.empty': 'Keine Dateien',
  'files.searchPlaceholder': 'In der Datei suchen…',
  'files.binary': 'Die Binärdatei kann nicht angezeigt werden',
  'files.back': 'Zurück',
  'files.loadError': 'Datei konnte nicht geladen werden',
  'files.previewEmpty': 'Wählen Sie eine Datei für die Vorschau',
  'changes.noRepo': 'Der Arbeitsbereich ist kein Git-Repository',
  'changes.gitMissing': 'git nicht gefunden',
  'changes.branch': 'Branch',
  'changes.clean': 'Sauberer Arbeitsbaum',
  'changes.filesCount': '{count} geänderte Dateien',
  'changes.added': 'Hinzugefügt',
  'changes.removed': 'Entfernt',
  'changes.untracked': 'Nicht verfolgte Dateien',
  'changes.empty': 'Keine Änderungen',
  'changes.staged': 'Gestaffelte Änderungen',
  'changes.stagedEmpty': 'Keine gestaffelten Änderungen',
  'changes.changes': 'Änderungen',
  'changes.conflicted': 'Konflikte',
  'changes.stage': 'Stagen',
  'changes.unstage': 'Unstagen',
  'changes.staging': 'Wird gestaged…',
  'changes.unstaging': 'Wird entstaged…',
  'changes.dirtyStageWarning': 'Nicht gespeicherte Editor-Änderungen sind nicht enthalten. Beim Stagen wird die gespeicherte Datei von der Festplatte verwendet.',
  'changes.opFailed': 'Der Git-Vorgang ist fehlgeschlagen',
  'changes.outsideWorkspace': 'Außerhalb des Arbeitsbereichs',
  'changes.discard': 'Änderungen verwerfen',
  'changes.discardTitle': 'Änderungen verwerfen?',
  'changes.discardConsequence': 'Dies stellt die gespeicherte Arbeitsdatei aus Git wieder her und kann von Harness Desktop nicht rückgängig gemacht werden.',
  'changes.discardConsequenceStaged': 'Dies stellt die Arbeitsdatei auf die gestaffelte Version wieder her. Gestaffelte Änderungen bleiben erhalten.',
  'changes.discardBlockedDirty': 'Diese Datei hat nicht gespeicherte Editor-Änderungen. Speichern oder verwerfen Sie den Editor-Entwurf, bevor Sie Änderungen von der Festplatte verwerfen.',
  'changes.discarding': 'Wird verworfen…',
  'changes.stateChanged': 'Der Git-Status hat sich geändert. Die Liste wurde aktualisiert; versuchen Sie es erneut.',
  'changes.cannotDiscard': 'Verwerfen ist für diesen Dateistatus nicht verfügbar.',
  'changes.cancel': 'Abbrechen',
  'changes.unstaged': 'Nicht gestaged',
  'changes.diffMode': 'Diff-Modus',
  'changes.noStagedChanges': 'Keine gestaffelten Änderungen',
  'changes.noUnstagedChanges': 'Keine nicht gestaffelten Änderungen',
  'changes.binaryChanged': 'Binärdatei geändert',
  'changes.diffTooLarge': 'Diff zu groß zum Anzeigen',
  'changes.prevFile': 'Vorherige Datei',
  'changes.nextFile': 'Nächste Datei',
  'changes.openFile': 'Datei öffnen',
  'changes.renameOnly': 'Nur umbenannt — keine Inhaltsänderung',
  'changes.diffSelectFile': 'Wählen Sie eine Datei, um ihren Diff anzuzeigen',
  'changes.diffLoading': 'Diff wird geladen…',
  'changes.untrackedNoDiff': 'Nicht verfolgte Datei — kein Git-Diff verfügbar',
  'changes.diffConflictReadOnly': 'Konfliktstatus ist schreibgeschützt',
  'terminal.noSession': 'Öffnen Sie eine Sitzung, um das Terminal zu verwenden',
  'terminal.new': 'Neues Terminal',
  'terminal.close': 'Terminal schließen',
  'terminal.inputHint': 'Hier eingeben und Enter drücken',
  'terminal.exited': 'Prozess beendet',
  'terminal.spawnError': 'Terminal konnte nicht gestartet werden',
  'plan.empty': 'Kein strukturierter Plan',
  'plan.pending': 'Ausstehend',
  'plan.active': 'Aktiv',
  'plan.completed': 'Abgeschlossen',
  'jobs.empty': 'Keine Hintergrundaufträge',
  'jobs.killed': 'Beendet',
  'jobs.failed': 'Fehlgeschlagen',
  'jobs.stopped': 'Gestoppt',
  'subagents.empty': 'Keine Subagenten',
  'subagents.main': 'Hauptagent',
  'subagents.running': 'Läuft',
  'subagents.completed': 'Abgeschlossen',
  'editor.backToConversation': 'Zurück zur Konversation',
  'editor.empty': 'Keine offenen Dateien',
  'editor.save': 'Speichern',
  'editor.saving': 'Speichern…',
  'editor.saved': 'Gespeichert',
  'editor.dirty': 'Ungespeicherte Änderungen',
  'editor.saveError': 'Speichern fehlgeschlagen',
  'editor.conflictState': 'Konflikt',
  'editor.conflictBody': 'Die Datei hat sich seit dem Öffnen auf dem Datenträger geändert. Neu laden, um den neueren Inhalt zu sehen, oder weiter bearbeiten.',
  'editor.conflictReload': 'Vom Datenträger neu laden',
  'editor.conflictKeep': 'Weiter bearbeiten',
  'editor.closeTab': 'Tab schließen',
  'editor.unsavedBody': 'Diese Datei hat ungespeicherte Änderungen.',
  'editor.unsavedCancel': 'Abbrechen',
  'editor.unsavedDiscard': 'Änderungen verwerfen',
  'editor.unsavedSave': 'Speichern',
  'editor.readOnly': 'Schreibgeschützt',
  'editor.large': 'Datei zu groß zum Bearbeiten',
  'editor.externalState': 'Extern geändert',
  'editor.externalBody': 'Diese Datei wurde auf der Festplatte geändert. Ihre Bearbeitungen bleiben im Speicher.',
  'editor.externalReload': 'Prüfen / Neu laden',
  'editor.externalKeep': 'Meine Änderungen behalten',
  'editor.deletedState': 'Gelöscht',
  'editor.deletedBody': 'Diese Datei wurde auf der Festplatte gelöscht. Der Tab behält den Inhalt; nichts wird automatisch neu erstellt.',
  'editor.deletedClose': 'Tab schließen',
  'editor.saveAll': 'Alle speichern',
  'quickOpen.placeholder': 'Dateien suchen…',
  'quickOpen.indexing': 'Workspace wird indexiert…',
  'quickOpen.empty': 'Keine Dateien in diesem Workspace',
  'quickOpen.noMatch': 'Keine passenden Dateien',
  'quickOpen.hint': '↑ ↓ navigieren · Enter öffnet · Esc schließt',
  'quitGuard.title': 'Nicht gespeicherte Änderungen',
  'quitGuard.body': 'Einige Dateien haben ungespeicherte Änderungen. Jetzt beenden?',
  'quitGuard.cancel': 'Abbrechen',
  'quitGuard.discard': 'Verwerfen und beenden',
  'quitGuard.saveAll': 'Alle speichern und beenden',
  'quitGuard.saveFailed': 'Einige Dateien konnten nicht gespeichert werden (veraltete Version). Nichts wurde verworfen.',
}
/** Brazilian Portuguese dictionary, complete against the English key set. */
export const ptBr: Record<DesktopStringKey, string> = {
  'onboarding.welcome.title': 'Bem-vindo ao Harness Desktop',
  'onboarding.welcome.body': 'Programação com IA baseada no DeepSeek Harness. Cliente de desktop não oficial.',
  'onboarding.welcome.continue': 'Continuar',
  'onboarding.provider.title': 'Conectar o DeepSeek',
  'onboarding.provider.apiKey': 'Chave de API',
  'onboarding.provider.baseUrl': 'URL base (opcional)',
  'onboarding.provider.save': 'Salvar nas Chaves',
  'onboarding.back': 'Voltar',
  'onboarding.workspace.title': 'Escolher um projeto',
  'onboarding.workspace.body': 'Selecione a pasta em que o Harness vai trabalhar. O seletor nativo do macOS será aberto em seguida.',
  'onboarding.workspace.pick': 'Abrir seletor de pasta',
  'status.starting': 'Iniciando o Harness…',
  'status.running': 'Conectado',
  'status.restarting': 'Reiniciando o Harness…',
  'status.stopped': 'Harness parado',
  'status.failed': 'Harness indisponível',
  'status.stopping': 'Parando o Harness…',
  'failure.title': 'O Harness parou inesperadamente.',
  'failure.restart': 'Reiniciar o Harness',
  'failure.logs': 'Abrir registros',
  'settings.language': 'Idioma',
  'settings.language.system': 'Sistema',
  'settings.language.english': 'English',
  'settings.language.italian': 'Italiano',
  'settings.language.chinese': 'Chinês',
  'settings.language.spanish': 'Espanhol',
  'settings.language.french': 'Francês',
  'settings.language.german': 'Alemão',
  'settings.language.portuguese': 'Português (Brasil)',
  'settings.advanced': 'Avançado',
  'settings.desktopVersion': 'Versão do desktop',
  'settings.harnessVersion': 'Versão do Harness',
  'settings.protocol': 'Protocolo do desktop',
  'settings.runtimeState': 'Estado do tempo de execução',
  'settings.restart': 'Reiniciar o Harness',
  'settings.logs': 'Abrir registros',
  'settings.diagnostics': 'Copiar diagnóstico',
  'settings.title': 'Ajustes',
  'settings.close': 'Fechar',
  'credentials.title': 'Credenciais do DeepSeek',
  'credentials.configured': 'Chave de API salva nas Chaves do macOS.',
  'credentials.notConfigured': 'Nenhuma chave de API configurada.',
  'credentials.replace': 'Substituir chave de API',
  'credentials.replacePlaceholder': 'Nova chave de API',
  'credentials.replaceSave': 'Salvar',
  'credentials.remove': 'Remover chave de API',
  'credentials.removeConfirm': 'Remover a chave de API salva? O assistente deixará de autenticar até que uma nova chave seja salva.',
  'credentials.removeConfirmYes': 'Remover',
  'credentials.removeConfirmNo': 'Cancelar',
  'settings.baseUrl': 'URL base',
  'settings.baseUrlPlaceholder': 'https://api.deepseek.com',
  'settings.baseUrlSave': 'Salvar',
  'settings.baseUrlInvalid': 'A URL base deve usar https://',
  'settings.copy': 'Copiar',
  'notification.approval': 'Aprovação necessária',
  'notification.approvalBody': 'O Harness está aguardando uma decisão de permissão.',
  'notification.question': 'Resposta necessária',
  'notification.questionBody': 'O Harness fez uma pergunta e está aguardando uma resposta.',
  'notification.taskCompleted': 'Tarefa concluída',
  'notification.taskCompletedBody': 'O assistente concluiu a tarefa atual.',
  'notification.runtimeFailed': 'O Harness parou inesperadamente',
  'notification.runtimeFailedBody': 'Abra o Harness Desktop para ver as opções de recuperação.',
  'error.credentialEmpty': 'A chave de API não pode estar vazia',
  'error.unknown': 'Algo deu errado',
  'inspector.toggle': 'Inspetor',
  'inspector.files': 'Arquivos',
  'inspector.changes': 'Alterações',
  'inspector.terminal': 'Terminal',
  'inspector.plan': 'Plano',
  'inspector.jobs': 'Tarefas',
  'inspector.subagents': 'Subagentes',
  'files.refresh': 'Atualizar',
  'files.reveal': 'Mostrar no Finder',
  'files.empty': 'Nenhum arquivo',
  'files.searchPlaceholder': 'Pesquisar no arquivo…',
  'files.binary': 'O arquivo binário não pode ser exibido',
  'files.back': 'Voltar',
  'files.loadError': 'Não foi possível carregar o arquivo',
  'files.previewEmpty': 'Selecione um arquivo para visualizar',
  'changes.noRepo': 'O espaço de trabalho não é um repositório Git',
  'changes.gitMissing': 'git não encontrado',
  'changes.branch': 'Ramo',
  'changes.clean': 'Árvore de trabalho limpa',
  'changes.filesCount': '{count} arquivos alterados',
  'changes.added': 'Adições',
  'changes.removed': 'Remoções',
  'changes.untracked': 'Arquivos não rastreados',
  'changes.empty': 'Sem alterações',
  'changes.staged': 'Alterações em stage',
  'changes.stagedEmpty': 'Nada em stage',
  'changes.changes': 'Alterações',
  'changes.conflicted': 'Conflitos',
  'changes.stage': 'Adicionar ao stage',
  'changes.unstage': 'Remover do stage',
  'changes.staging': 'Adicionando ao stage…',
  'changes.unstaging': 'Removendo do stage…',
  'changes.dirtyStageWarning': 'Alterações não salvas no editor não são incluídas. O stage usará o arquivo salvo em disco.',
  'changes.opFailed': 'A operação do Git falhou',
  'changes.outsideWorkspace': 'Fora do espaço de trabalho',
  'changes.discard': 'Descartar alterações',
  'changes.discardTitle': 'Descartar as alterações?',
  'changes.discardConsequence': 'Isso restaura o arquivo salvo do Git e o Harness Desktop não pode desfazer.',
  'changes.discardConsequenceStaged': 'Isso restaura o arquivo para a versão em stage. As alterações em stage permanecem.',
  'changes.discardBlockedDirty': 'Este arquivo tem alterações não salvas no editor. Salve ou descarte o rascunho do editor antes de descartar as alterações do disco.',
  'changes.discarding': 'Descartando…',
  'changes.stateChanged': 'O estado do Git mudou. A lista foi atualizada; tente novamente.',
  'changes.cannotDiscard': 'Descartar não está disponível para este estado do arquivo.',
  'changes.cancel': 'Cancelar',
  'changes.unstaged': 'Sem stage',
  'changes.diffMode': 'Modo de diff',
  'changes.noStagedChanges': 'Nenhuma alteração em stage',
  'changes.noUnstagedChanges': 'Nenhuma alteração sem stage',
  'changes.binaryChanged': 'Arquivo binário alterado',
  'changes.diffTooLarge': 'Diff grande demais para exibir',
  'changes.prevFile': 'Arquivo anterior',
  'changes.nextFile': 'Próximo arquivo',
  'changes.openFile': 'Abrir arquivo',
  'changes.renameOnly': 'Somente renomeação — sem mudança de conteúdo',
  'changes.diffSelectFile': 'Selecione um arquivo para ver o diff',
  'changes.diffLoading': 'Carregando diff…',
  'changes.untrackedNoDiff': 'Arquivo não rastreado — nenhum diff do Git disponível',
  'changes.diffConflictReadOnly': 'o estado de conflito é somente leitura',
  'terminal.noSession': 'Abra uma sessão para usar o terminal',
  'terminal.new': 'Novo terminal',
  'terminal.close': 'Fechar terminal',
  'terminal.inputHint': 'Digite aqui e pressione Enter',
  'terminal.exited': 'Processo encerrado',
  'terminal.spawnError': 'Não foi possível iniciar o terminal',
  'plan.empty': 'Nenhum plano estruturado',
  'plan.pending': 'Pendente',
  'plan.active': 'Ativo',
  'plan.completed': 'Concluído',
  'jobs.empty': 'Nenhuma tarefa em segundo plano',
  'jobs.killed': 'Encerrada',
  'jobs.failed': 'Falhou',
  'jobs.stopped': 'Parada',
  'subagents.empty': 'Nenhum subagente',
  'subagents.main': 'Agente principal',
  'subagents.running': 'Em execução',
  'subagents.completed': 'Concluído',
  'editor.backToConversation': 'Voltar à conversa',
  'editor.empty': 'Nenhum arquivo aberto',
  'editor.save': 'Salvar',
  'editor.saving': 'Salvando…',
  'editor.saved': 'Salvo',
  'editor.dirty': 'Alterações não salvas',
  'editor.saveError': 'Falha ao salvar',
  'editor.conflictState': 'Conflito',
  'editor.conflictBody': 'O arquivo mudou no disco desde que foi aberto. Recarregue para ver o conteúdo mais recente ou continue editando.',
  'editor.conflictReload': 'Recarregar do disco',
  'editor.conflictKeep': 'Continuar editando',
  'editor.closeTab': 'Fechar aba',
  'editor.unsavedBody': 'Este arquivo tem alterações não salvas.',
  'editor.unsavedCancel': 'Cancelar',
  'editor.unsavedDiscard': 'Descartar alterações',
  'editor.unsavedSave': 'Salvar',
  'editor.readOnly': 'Somente leitura',
  'editor.large': 'Arquivo grande demais para editar',
  'editor.externalState': 'Alterado externamente',
  'editor.externalBody': 'Este arquivo mudou no disco. Suas edições permanecem na memória.',
  'editor.externalReload': 'Revisar / Recarregar',
  'editor.externalKeep': 'Manter minhas alterações',
  'editor.deletedState': 'Excluído',
  'editor.deletedBody': 'Este arquivo foi excluído do disco. A aba mantém o conteúdo; nada é recriado automaticamente.',
  'editor.deletedClose': 'Fechar aba',
  'editor.saveAll': 'Salvar tudo',
  'quickOpen.placeholder': 'Pesquisar arquivos…',
  'quickOpen.indexing': 'Indexando o workspace…',
  'quickOpen.empty': 'Nenhum arquivo neste workspace',
  'quickOpen.noMatch': 'Nenhum arquivo correspondente',
  'quickOpen.hint': '↑ ↓ navegar · Enter abre · Esc fecha',
  'quitGuard.title': 'Alterações não salvas',
  'quitGuard.body': 'Alguns arquivos têm alterações não salvas. Sair agora?',
  'quitGuard.cancel': 'Cancelar',
  'quitGuard.discard': 'Descartar e sair',
  'quitGuard.saveAll': 'Salvar tudo e sair',
  'quitGuard.saveFailed': 'Não foi possível salvar alguns arquivos (versão desatualizada). Nada foi descartado.',
}

/**
 * Translate one desktop key for a language.
 * @param language - the resolved desktop language.
 * @param key - the desktop string key.
 * @returns the translated string.
 */
export function desktopText(language: DesktopLanguage, key: DesktopStringKey): string {
  const dicts: Record<DesktopLanguage, Record<DesktopStringKey, string>> = { en, zh, it, es, fr, de, 'pt-BR': ptBr }
  return dicts[language][key]
}

/**
 * React seat over the desktop language store.
 * @returns the live language and its translation function.
 */
export function useDesktopStrings(): { language: DesktopLanguage; t: (key: DesktopStringKey) => string } {
  const language = useSyncExternalStore(
    listener => desktopLocale.subscribe(() => { listener() }),
    () => desktopLocale.get(),
  )
  return { language, t: key => desktopText(language, key) }
}

/**
 * Live macOS appearance for the desktop-owned surfaces.
 * @returns the current light or dark appearance, following system changes.
 */
export function useDesktopAppearance(): 'light' | 'dark' {
  const resolve = (): 'light' | 'dark' => {
    if (typeof window.matchMedia !== 'function') return 'light'
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
  }
  return useSyncExternalStore(
    (listener) => {
      if (typeof window.matchMedia !== 'function') return () => {}
      const query = window.matchMedia('(prefers-color-scheme: dark)')
      query.addEventListener('change', listener)
      return () => { query.removeEventListener('change', listener) }
    },
    resolve,
  )
}

/**
 * Dialog palette for the current appearance.
 * @param appearance - the current light or dark appearance.
 * @returns the color tokens for the desktop dialogs.
 */
export function desktopPalette(appearance: 'light' | 'dark'): {
  dialog: string
  text: string
  muted: string
  input: string
  inputBorder: string
  code: string
} {
  return appearance === 'dark'
    ? {
      dialog: '#1e2026',
      text: '#e8eaef',
      muted: '#9aa1ad',
      input: '#17181d',
      inputBorder: '#3a3f49',
      code: '#17181d',
    }
    : {
      dialog: '#ffffff',
      text: '#181a20',
      muted: '#4a4f59',
      input: '#ffffff',
      inputBorder: '#d0d4dc',
      code: '#f4f5f7',
    }
}
